-- Deshabilitar RLS completamente para todas las tablas
-- Ejecutar en Supabase SQL Editor

ALTER TABLE tournament DISABLE ROW LEVEL SECURITY;
ALTER TABLE team DISABLE ROW LEVEL SECURITY;
ALTER TABLE player DISABLE ROW LEVEL SECURITY;
ALTER TABLE match_day DISABLE ROW LEVEL SECURITY;
ALTER TABLE match DISABLE ROW LEVEL SECURITY;
ALTER TABLE goal DISABLE ROW LEVEL SECURITY;
ALTER TABLE card DISABLE ROW LEVEL SECURITY;
ALTER TABLE sanction DISABLE ROW LEVEL SECURITY;
ALTER TABLE document DISABLE ROW LEVEL SECURITY;
ALTER TABLE news DISABLE ROW LEVEL SECURITY;
ALTER TABLE admin_user DISABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log DISABLE ROW LEVEL SECURITY;

SELECT 'RLS deshabilitado en todas las tablas' AS resultado;